spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/aicodereview?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${MYSQL_USERNAME:aicodereview}
    password: ${MYSQL_PASSWORD:aicodereview}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
