spring:
  config:
    import: optional:file:.env[.properties]
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:aicodereview;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
          max-tokens: 4096

aicodereview:
  ai:
    provider: openai

server:
  port: 8081